### ISSUE TITLE
Lily58/light - Not detected by Via

### ISSUE THREAD

**Issue by AdsumSOK** [the-via/keyboards#1066]
Hello,
It seams that the board lily58/light is not detected by VIA.
It seams that the vendor is not in the ‘known list’ of Via.
(Changing the product / vendor id by the ‘rev1’ product / vendor works)
Can you check it please ?
#define VENDOR_ID       0x7983
#define PRODUCT_ID      0x4C4C // "LL"

**Comment by yiancar** [comment]
Someone has to create the .json definition for this keyboard:)
