### ISSUE TITLE
kbd67 mkii rgb v3 missing lighting tab

### ISSUE THREAD

**Issue by lormanlau** [the-via/keyboards#1131]
In the GUI the tabs to the left for the KBD67 mkii rgb v3 is missing the lighting tab.

https://github.com/the-via/keyboards/blob/master/src/kbdfans/kbd67mkii/kbd67mkiirgbv3.json
https://github.com/qmk/qmk_firmware/blob/master/keyboards/kbdfans/kbd67/mkiirgb/v3/config.h

**Comment by kb-elmo** [comment]
The lighting tab is disabled on purpose for that board since VIAs lighting control only supports RGB underglow PCBs.

It does not work with per-key LED keyboards and would cause the app to crash.
