### ISSUE TITLE
New board layouts are crashing the GUI

### ISSUE THREAD

**Issue by LilithWasTaken** [the-via/keyboards#1141]
As per main thread issue #115(https://github.com/the-via/releases/issues/115),#128(https://github.com/the-via/releases/issues/128), and #153 (https://github.com/the-via/releases/issues/153). As this issue has been present for quite a long time I was wondering when there might be a resolution to this?

**Comment by yiancar** [comment]
Can you please tell me what keyboard your using? Most likely this is because either the keyboard does not exist in VIA or because VIA is not aware it has lighting. Ofcource it might be because it is using an older version on QMK as well.

**Comment by yiancar** [comment]
As we might have figured out most likely all of this have to do with the vendor not submitting the necessary json file to the repository or enabling VIA on the qmk firmware. I will close this for now please feel free to open another issue if a json is present and via is enabled in QMK:)
