### ISSUE TITLE
Ctrl when held, Esc when tapped?

### ISSUE THREAD

**Issue by jesseleite** [the-via/keyboards#1164]
Similar to the `KC_LSPO` mapping, is it possible to map a key to `Ctrl` when held, and `Esc` when tapped?

**Comment by davidk55** [comment]
I searched for the same and actually found out it is possible with pasting `MT(MOD_LCTL, KC_ESC)` into the `any` button (last button of `SPECIAL`) like it is described here: https://github.com/the-via/releases/issues/74

**Comment by jesseleite** [comment]
Oh neat!
