### ISSUE TITLE
Maartenwut Wonderland Wrong Key for Backspace

### ISSUE THREAD

**Issue by airyimbin** [the-via/keyboards#123]
The wrong key is set for non split backspace.
It's the second key not the first for non split backspace.

You have to split the backspace in layouts, then change the key for it to change correctly.

**Comment by Wilba6582** [comment]
@maartenwut Can you confirm this and make the change?

**Comment by Maartenwut** [comment]
Yes, it seems the wrong matrix position is used for the 2u backspace key. I'll fix it.

**Comment by airyimbin** [comment]
Thanks for the quick fix!
