### ISSUE TITLE
Keychron JSON files use center legend position for Space instead of top left

### ISSUE THREAD

**Issue by CrazyCoder** [the-via/keyboards#1277]
Please see https://github.com/vial-kb/vial-gui/issues/105.

It makes Space key invisible in Vial. They say it's a bug in Keychron JSON.

According to the [documentation](https://www.caniusevia.com/docs/layouts#switch-matrix-co-ordinates):
_The mapping from physical layout to switch matrix layout is defined by the top-left legend of the key_ 

Keychron uses center legend instead of a top left, making the Space key invisible.

CC @lalalademaxiya1.

It needs to be fixed for Q1, Q2 and Q3 (not yet available in this repository), plus all the upcoming Q-series keyboards from Keychron.
It would be great if the fixed JSON files are also uploaded on Keychron web site, I hope @lalalademaxiya1 can help with that.

**Comment by yiancar** [comment]
Hello!
Indeed this seems to be the issue. Please upload a patch for the fix and Ill merge it:)
