### ISSUE TITLE
CH572 support

### ISSUE THREAD

**Issue by pospanet** [the-via/keyboards#1296]
Hi there,
there is very popular 3 to 12 keys keyboard like [this](https://www.walmart.com/ip/USB-Mini-12-Key-Gaming-Keyboard-Programmable-Keys-with-2-Knobs-Custom-Shortcuts-White/793527197), yet you can find it on AliExpress for very reasonable price as well. Is it possible to add support for this keyboard, please? It is based on [WCH CH572 chip](https://w.electrodragon.com/w/WCH_Chips). Chip spec [here](https://www.cnx-software.com/2019/02/16/wch-ch572-risc-v-mcu-bluetooth-le/). Thanks

**Comment by kb-elmo** [comment]
VIA is just a GUI for the QMK firmware.  
To get VIA support the board would have to ported to QMK first. 

QMK currently has no support for the chip that this board uses and is very unlikely to get support for it at any point in the near future.  
So VIA on this board is not going to be possible for now.

**Comment by yiancar** [comment]
Exactly what was stated above:)
The VIA protocol is pretty straight forward so if someone can write firmware the above chip adding VIA is not that hard.
