### ISSUE TITLE
Porting my own keyboard

### ISSUE THREAD

**Issue by NatyanC** [the-via/keyboards#1322]
Hello, 

I built my own custom keyboard that i designed, and i wanted to use via. 
This keyboard is unique and i will be the only one having it.
Is it possible for me to port my keyboard into via by myself ? And if so, how can i do it ?

Thank you in advance.

**Comment by yiancar** [comment]
Hello there!
If its using QMK it should be pretty straight forwards. You have to enable VIA in QMK and then create a JSON file for VIA.
You dont even have to submit the file here, you can just keep it local and load it to VIA every time.

There is a few youtube videos you can watch and also read our docs at: caniusevia.com!
