### ISSUE TITLE
Mouse keys not mapped correctly

### ISSUE THREAD

**Issue by elagil** [the-via/keyboards#136]
There is an issue when setting mouse keys in VIA.

For example, setting `KC_MS_UP` on a key makes it do nothing. 
However, putting in its hex-code `0xF0` makes the mouse key work. Is this mapped incorrectly within VIA, or does it lack the necessary definitions?

**Comment by Wilba6582** [comment]
see https://github.com/the-via/releases/issues/16

**Comment by elagil** [comment]
Sorry, just found it.
