### ISSUE TITLE
Vendor Definitions

### ISSUE THREAD

**Issue by orionstudt** [the-via/keyboards#1416]
Can someone help me understand where the vendors are defined? I'm trying to understand why the keyboard files under "Wuque" have a handful of different `vendorId` values when I would expect them to each be the same for "Wuque." Are vendor ID -> definition mappings in a different repository?

**Comment by yiancar** [comment]
Yes so VIA just checks for VID and PID to understand which keyboard is connected. This is defined in the firmware of the keyboard which is in QMK:)
