### ISSUE TITLE
GMMK2 p65 ANSI shows incorrect keymap on configure screen

### ISSUE THREAD

**Issue by the-ashh** [the-via/keyboards#1497]
When using the firmware for the GMMK2 p65 ANSI from the [firmware page](https://www.caniusevia.com/docs/download_firmware), as well as building from source myself, the keymap that shows up on VIA configure screen is very incorrect. 

![image of incorrect keymap](https://ashlyn.gay/VIA_tuhPCAe9FZ.png)

All of the keys work correctly, so not sure if this is a problem with #1471, or something else.

**Comment by Xelus22** [comment]
Looks like they have flipped the <row,col> number around. They have put <col,row> instead by accident. Will require the maker @adophoxia to fix this.

**Comment by adophoxia** [comment]
Not home at the moment, but I'll get to this when I can sometime today, @Xelus22. I accidentally thought that the matrix indexes were reversed since VIA gave me an error about not having the correct amount of rows and cols when loading it through the Design tab. @the-ashh, if it's possible, would it be fine to send you a revised JSON to help verify that the keys are displayed properly?

**Comment by the-ashh** [comment]
> @the-ashh, if it's possible, would it be fine to send you a revised JSON to help verify that the keys are displayed properly?

That works for me! To test it, would i just load the JSON in the design tab?

**Comment by adophoxia** [comment]
@the-ashh, yes. I'll be sure to let you know when I upload the JSONs for you to test.

**Comment by adophoxia** [comment]
@the-ashh, I've made a new PR to [fix the JSONs for the p65 variants for the GMMK 2](https://github.com/the-via/keyboards/pull/1505). You can checkout the respective fork of mine to see if it correctly displays the keymap for you.

**Comment by the-ashh** [comment]
@adophoxia that fix works for me! Thanks a bunch!

**Comment by adophoxia** [comment]
You're welcome.

**Comment by adophoxia** [comment]
Actually, @the-ashh, is the Caps Lock from your screenshot supposed to be F13?

**Comment by the-ashh** [comment]
Yep, I use F13 for certain other things, don't find myself using caps lock much lol

**Comment by adophoxia** [comment]
Ah, ok. I thought I might've screwed up something in the process of redoing the JSONs.

**Comment by Xelus22** [comment]
Fixed with #1505
