### ISSUE TITLE
Layer issue 

### ISSUE THREAD

**Issue by 20RL** [the-via/keyboards#153]
When trying to programme the " | \ " `KC_BSLS` button on a new layer it functions as a hashtag button.

**Comment by sigprof** [comment]
If you are using a non-US keyboard layout on your computer (especially one of layouts that requires using the ISO physical keyboard layout with an extra key near the left Shift), you should use the `KC_NUBS` key (NUBS on the Special page) to get the backslash and pipe characters. In this case the `KC_BSLS` key is usually treated as `KS_NUHS` by the OS on your computer, which gives the hash character with many of national keyboard layouts.
