### ISSUE TITLE
A knob configuration doesn't work with Keychron Q8

### ISSUE THREAD

**Issue by highwide** [the-via/keyboards#1619]
Thank you for the awesome product!!

I bought a Keychron Q8 knob edition and tried to configure it with VIA.
It worked almost keys but the knob doesn't.

When the knob in the display of VIA clicked, these error messages showed in the console.

```
index.f7c0fa75fdf0cf0c04c1.js:2 Command for 08a2eeca-b1cd-408a-8e60-831e3a89240f: (5) [0, 20, 0, 0, 1]0: 01: 202: 03: 04: 1length: 5[[Prototype]]: Array(0) Bad Resp: Uint8Array(32) [8, 128, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']0: 81: 1282: 1913: 04: 05: 06: 07: 08: 09: 010: 011: 012: 013: 014: 015: 016: 017: 018: 019: 020: 021: 022: 023: 024: 025: 026: 027: 028: 029: 030: 031: 0buffer: ArrayBuffer(32)  byteLength: 32byteOffset: 0length: 32Symbol(Symbol.toStringTag): "Uint8Array"[[Prototype]]: TypedArray
_hidCommand @ index.f7c0fa75fdf0cf0c04c1.js:2
await in _hidCommand (async)
flushQueue @ index.f7c0fa75fdf0cf0c04c1.js:2
(anonymous) @ index.f7c0fa75fdf0cf0c04c1.js:2
hidCommand @ index.f7c0fa75fdf0cf0c04c1.js:2
getEncoderValue @ index.f7c0fa75fdf0cf0c04c1.js:2
(anonymous) @ index.f7c0fa75fdf0cf0c04c1.js:578
(anonymous) @ index.f7c0fa75fdf0cf0c04c1.js:578
ai @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Es @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
S @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
T @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
I.<computed> @ 445.bed1a9f49476173ef538.js:1
M @ 445.bed1a9f49476173ef538.js:1
T @ 445.bed1a9f49476173ef538.js:1
index.f7c0fa75fdf0cf0c04c1.js:2 Uncaught (in promise) Error: Receiving incorrect response for command
    at Sn._hidCommand (index.f7c0fa75fdf0cf0c04c1.js:2:54957)
    at async Sn.flushQueue (index.f7c0fa75fdf0cf0c04c1.js:2:54348)
_hidCommand @ index.f7c0fa75fdf0cf0c04c1.js:2
await in _hidCommand (async)
(anonymous) @ index.f7c0fa75fdf0cf0c04c1.js:578
ai @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Es @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
S @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
T @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
I.<computed> @ 445.bed1a9f49476173ef538.js:1
M @ 445.bed1a9f49476173ef538.js:1
T @ 445.bed1a9f49476173ef538.js:1
```

<img width="1671" alt="Screen Shot 2023-01-06 at 23 45 27" src="https://user-images.githubusercontent.com/1495423/211035157-9207afcf-87f6-4f6a-ad45-a8bfa68d0140.png">

And I tried to upload the keymap json which is downloaded from Keychron's official site: https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q8-keyboard
But after that, VIA didn't show my Keychron in the "CONFIGURE" display.

<img width="1117" alt="Screen Shot 2023-01-06 at 23 59 40" src="https://user-images.githubusercontent.com/1495423/211038038-16b92638-60d7-4ec9-9619-b5670d88770d.png">

I tried it from the app for web and the app for Mac, but the results are same.

I'm not sure which VIA or Keychron causes.
So let me share to @lalalademaxiya1 who created this pull request too.
=> https://github.com/the-via/keyboards/pull/1549

**Comment by yiancar** [comment]
please also flash the latest via file on your keyboard. the dynamic encoder is a new feature on qmk.
but @lalalademaxiya1 should be able to help more.
