### ISSUE TITLE
Keychron Q6 - ISO - encoder (knob) and key "fn+J+Z" not working

### ISSUE THREAD

**Issue by AndroSteph** [the-via/keyboards#1677]
Hello,

I have had my Q6 keyboard for a few days and if I flash with the firmware from Keychron "q6_iso_knob_V1.4.bin" I can use the "reset" keys which are "fn+J+Z" (as indicated in the Keychron DOC (https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q6-keyboard). However, if I use the firmware here "keychron_q6_iso_encoder_via.bin", this combination of keys "fn+J+Z" no longer works, nor does it work for the "fn" key. I don't know what to do, which keys to use to do this "reset".

If I flash again with the "q6_iso_knob_V1.4.bin" the combination for reset "fn+J+Z" works 

I flashed with the "q6_iso_knob_V1.4.bin" only for all the light effects to work ... with the original firmwar (version?) they worked only up to number 13 (approximately)

Do you have the same problem? Or any idea how to solve it?

Thanks :-)

Sorry for my bad English :-(

**Comment by AndroSteph** [comment]
Precision, the firmware of VIA for my Keychron Q6, I downloaded it from https://www.caniusevia.com/docs/download_firmware

**Comment by yiancar** [comment]
Hello there This is more of a keychron problem:) Lets see if Keychrons maintainer can help: @lalalademaxiya1

**Comment by AndroSteph** [comment]
I closed the message https://github.com/the-via/releases/issues/246

and this one is still not resolved https://github.com/the-via/keyboards/issues/1677

**Comment by yiancar** [comment]
HE should be autotagged

**Comment by yiancar** [comment]
Hello, as this is not a VIA issue and @lalalademaxiya1 is not responding I will close this issue. Feel free to reach out to Keychron in some other way and report this.
This might help: https://www.keychron.com/pages/contact-us

**Comment by AndroSteph** [comment]
Sorry for putting this message maybe in a wrong section or my explanation (in English) is not precise enough (it's not my language)

I wanted to say that the **firmware v1.4 from Keychron works** https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q6-keyboard and the **firmware "VIA" does not work** https://www.caniusevia.com/docs/download_firmware

You can leave this ticket closed if you want, I just wanted to make this clarification and warn users that for this keyboard, a "Keychron Q6" it is no longer possible to use the official keys "fn+J+Z" to do a "reset" of the keyboard (which can be very annoying in case of problem).

I put back the "1.4v" from Keychon and the combination "fn+J+Z" works again.

Thank you for taking the time to try to help me.

**Comment by yiancar** [comment]
OH! I understand. The firmware from there are just the default compilation from QMK repo. What this means is that the default firmware is not correctly setup. The firmware from keychron website probably has some changes.

**Comment by AndroSteph** [comment]
I found the answer to my question here

https://github.com/qmk/qmk_firmware/tree/master/keyboards/keychron/q6

"**Reset Key**: Hold down the key located at K00, commonly programmed as Esc while plugging in the keyboard."

One of the differences I clearly noticed is that with the **original combination (fn+J+Z)** the LEDs of the keys become all red, while with this **new method ("reset")** they don't, and this makes it impossible to see if the requested action has been performed or not.

And this is what brought me here to post my question.

**Comment by AndroSteph** [comment]
Hello and thank you for your message.

I think I found my happiness by not having the "fn+J+Z" where you have to remove the "space bar" to be able to press the physical button under this bar just to flash.

With the "ESC + USB cable connection" I am perfectly happy to be able to flash the firmware without removing the space bar and therefore easily and quickly. :-)
