### ISSUE TITLE
Please add Keychron Q1 v2 (encoder) to keyboards list

### ISSUE THREAD

**Issue by kpervin** [the-via/keyboards#1703]
Currently only the Keychron Q1 v1 is in the list of keyboards. Please add [Keychron Q1 v2 (encoder)](https://github.com/qmk/qmk_firmware/tree/master/keyboards/keychron/q1) to the list of keyboards so that it can be automatically recognized in VIA.

**Comment by KiNG-GH** [comment]
@lalalademaxiya1 Would u kindly help with it
Thx a lot!

**Comment by lalalademaxiya1** [comment]
@KiNG-GH Hi! In fact, we are already doing related work on q1v2, but q1v2 uses a different MCU from v1, and it will take a long time to merge into the qmk master. See details here(qmk/qmk_firmware#19307)

**Comment by kpervin** [comment]
Thanks! I would help but I wouldn't have the first clue on where to start.

**Comment by yiancar** [comment]
I consider this closed please contact Keychron directly if you would like
