### ISSUE TITLE
How to add a keyboard?

### ISSUE THREAD

**Issue by kvqn** [the-via/keyboards#1724]
Sorry for creating an issue for just a question.
I want to add my Redragon K617 keyboard to the list of supported keyboards and I could not find a contributor's guide. Can someone point me to the right resources ?

**Comment by yiancar** [comment]
There is multiple guides on youtube also you should read the docs at: https://www.caniusevia.com/docs/specification

**Comment by biggestsonicfan** [comment]
Is there a reason this information can't be added to the README of this repo instead of having a single hotlink to a nonexistant image?
