### ISSUE TITLE
KBD67 MKII ISO RGB : LUFA Disk or bootloader mode not working

### ISSUE THREAD

**Issue by H3lli0n** [the-via/keyboards#1754]
Hi,

From the default firmware when we press ESC and plug the keyboard, a LUFA disk is created for upgrading firmware as described here : https://docs.google.com/document/d/1KhxKkIncCOCKx9nUxhKok5NISU-FQ4tTHofdl_noNZQ/edit

I flashed to newer VIA firmware and I'm unable to enter bootloader mode and LUFA disk is not created. I've had to press reset buton and I switch back to the KBDFans firmware posted in their documentation.

Regards

**Comment by Xelus22** [comment]
Hi please refer back to the KBDFans support server/customer support. We don't deal with these are this is just the GUI. It seems your firmware or bootloader itself has been messedup somewhere.
