### ISSUE TITLE
Did via only support Wired connection？

### ISSUE THREAD

**Issue by TalentedBastard** [the-via/keyboards#2196]
I use via to change the key of my zoom75，I can connect normally using wired，but buletooth is not connected，Authorize device cant find any keyboard

My keyboard：zoom75
My device：macos Sonoma 14.1 and windows11

**Comment by LXF-YZP** [comment]
> I use via to change the key of my zoom75，I can connect normally using wired，but buletooth is not connected，Authorize device cant find any keyboard
> 
> My keyboard：zoom75 My device：macos Sonoma 14.1 and windows11

Bluetooth issues won't get solved here, you can go to qmk Community Reaction, or qmk discord. In fact, you should ask zoom75 group buyers
