### ISSUE TITLE
Instructions for adding support for KeyChron Q3 Pro

### ISSUE THREAD

**Issue by jeffreyzhang92** [the-via/keyboards#2218]
Hello I am new to custom keyboards - are there instructions for how to format the request? I can't figure out how to get the keymaps json. Thanks!

**Comment by Xelus22** [comment]
You can check previous PRs. There are also some issues with Keychron wireless keyboards and won't be accepted into VIA until official QMK support.

**Comment by jeffreyzhang92** [comment]
I saw some previous PRs and they all have a json that is the main part that I am asking about.

But if I understand what you're saying, even if I constructed this json, it would be moot?

**Comment by Xelus22** [comment]
> I saw some previous PRs and they all have a json that is the main part that I am asking about.
> 
> But if I understand what you're saying, even if I constructed this json, it would be moot?

Effectively yes, _until_ keychron are able to upstream their keyboard to QMK master

**Comment by jeffreyzhang92** [comment]
Thank you! I followed this page on Keychron's website @shyam-patel-kira :

https://www.keychron.com/pages/how-to-use-via-to-pair-with-keychron-q-series-keyboard#
