### ISSUE TITLE
EK21 Keypad gets Incorrect Response on "DYNAMIC_KEYMAP_SET_BUFFER" when loading saved keymap JSON files

### ISSUE THREAD

**Issue by nonplayer** [the-via/keyboards#2237]
I have tried with three different EK21 keypads, all reset to factory settings. It's used USB cables to connect, and repeated the process on both a Win10 desktop and a Win11 laptop, each time attempting with both the local 3.0.0 installation, then the usevia.app site, and again via the via.etove.app site.

Reproduction Steps:

1. Open Via app (either the local installation, or the usevia.app site)
2. Follow official Epomaker steps for loading hardware JSON (download JSON, enable Design tab, set use V2 defs, import)
3. Open Configure Tab, then adjust and confirm desired layout changes
4. Open "Save + Load" and Save the layout JSON
5. Hit "Load" and attempt to load the same JSON

Results: error (below copied from webapp, but otherwise identical in local app):

```
10:08:27.944
Command Name: DYNAMIC_KEYMAP_SET_BUFFER
Command: 19 0 0 28 0 41 95 16 0 43 0 42 0 95 0 96 0 97 0 87 0 89 0 90 0 91 0 42 0 83 0 84
Response: 1 0 9 28 0 41 95 16 0 43 0 42 0 95 0 96 0 97 0 87 0 89 0 90 0 91 0 42 0 83 0 84
Device: EPOMAKER EK21
Vid: 0x320F
Pid: 0x5055

10:08:27.968
Error: Receiving incorrect response for command
at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f35a099a.js:3:9407)
at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f35a099a.js:3:8661)
Device: EPOMAKER EK21
Vid: 0x320F
Pid: 0x5055
```

On the surface it appears that this is from the first three number sets of the Command/Response conflicting.

Note that all manual keymap changes to any particular device function as expected. The error only occurs when attempting to load a saved keymap JSON file, either to the same device or to a different one.

I do hope this is the proper place to report this. Thank you.

**Comment by Xelus22** [comment]
This is not an issue with VIA. This is an issue with your firmware. 
You will have to contact Epomaker to fix this. 

Official VIA support requires the keyboard to be in the QMK master. Epomaker does not open-source their firmware and also breaks the licensing of QMK (GPLv2 iirc)

**Comment by nonplayer** [comment]
Makes sense, thanks for the information.

**Comment by seh** [comment]
I see the same problem on a new WOBKEY _Crush 80_, even after updating it to the latest firmware.
