### ISSUE TITLE
Default mod tap timing in VIA?

### ISSUE THREAD

**Issue by yoyomancer** [the-via/keyboards#2310]
Are all keyboards found in the official repo built with the same mod tap delay? I have a rev2.8 Iris that I've been using for a few years now, where the delay is perfect for me, but I have no idea what it actually is. I would love to have the correct number so I can set up the same delay on my Sofle RGB.

To expand a bit more: I didn't find an official VIA firmware on usevia.com for the Sofle RGB, so I used the one I found from beekeeb, and the mod tap delay on that one is ridiculously low, it feels like sub 100ms low, and triggers nearly every time I press my Enter key (I use `LAlt(Enter)` on my left thumb).

**Comment by Xelus22** [comment]
Default is here in QMK docs
https://docs.qmk.fm/tap_hold#tapping-term

**Comment by yoyomancer** [comment]
Excellent, thank you!

I've no idea what they used in [this one](https://docs.beekeeb.com/build-guide/sofle-rgb-v2.1-soflekeyboard-build-log-guide-with-photos#via-firmware-with-72-rgb-leds-enabled), but it's way too short for me.
