### ISSUE TITLE
Please Add Keychron K3 Max

### ISSUE THREAD

**Issue by ronnybruechner** [the-via/keyboards#2321]
I bought the K3 Max when it was released almost 8 months ago.

To this day, there is no firmware, let alone any support for this keyboard on the usevia.app page.
The keyboard is connected by cable and every key works.
But nothing is read out, nor can I make settings for the RGB lighting per key, for example.

Really annoying.
![K3 Max connected to pc](https://github.com/user-attachments/assets/380d2aca-2973-4187-a718-f7c421f8813d)
![keytest](https://github.com/user-attachments/assets/3d6dfb40-57f7-4b72-8c9f-140368766e62)
![no connect](https://github.com/user-attachments/assets/c5e0f5d7-9bc3-436c-902d-e7bde589ffb5)
![usevia connect](https://github.com/user-attachments/assets/fc78c38c-0153-408d-aa59-6ae8420ea5cb)

**Comment by Xelus22** [comment]
Unfortunately due to requirements, there is no official support of VIA for most Keychron Wireless Keyboards.

Keychron is recommending users use their own keyboard remapping tool (which is built on VIA):
https://launcher.keychron.com/
