### ISSUE TITLE
Add Keyboard Compatibility: Keychron C3 Pro

### ISSUE THREAD

**Issue by FeAspers** [the-via/keyboards#2325]
Hello, I bought my keyboard on Amazon and I specifically looked for one with QMK-Enabled. Even the instruction manual said to go to [caniusevia.com](https://www.caniusevia.com/) and download the latest firmware, however there is no compatibility for the Keychron C3 Pro Tenkeyless Mechanical Keyboard.
### Keyboard Details:
Manufacturer: Keychron
Model: C3 Pro Tenkeyless Mechanical Keyboard
Connection Type: Wired USB
TKL Layout
Gasket Mount Design
Open Source Firmware {QMK VIA}
Dedicated Siri or Cortana Key
Light Effects {14+ Light effects to switch from}

### Technical Specifications:
Key Count: 87 (Tenkeyless)
Key Switches: Red Switch
Key Rollover: NKRO (N-Key Rollover)
Backlighting: RGB (Optional)
Microcontroller Model: idk 
Matrix Layout: idk
Layout: TKL
Switch Type: Mechanical
Width: 137.8 mm
Length: 364.6
Front Height: 20.6 mm (Without keycaps) - 31.8 mm (with keycaps installed)
Back Height: 29.9 mm (Without keycaps) - 41.8 (with keycaps installed)
Keyboard feet height: 1.3 mm
Angle: 4/6/8.7 degree

### Reference Links:
Amazon Link: [Amazon](https://www.amazon.com/dp/B0CBWH8VPN/ref=twister_B0CH8FL73T?_encoding=UTF8&psc=1)

### Keychron Information: 
Keychron, Inc.
Dover, DE 19901, United States
find us at: 
https://www.keychron.com
Support@keychron.com
[Facebook] @ keychron
[Instagram] @ keychron 
[Twitter/X] @ keychronMK 
Designed by Keychron
Made in China

### Reference Images:
![20240729_004557](https://github.com/user-attachments/assets/ee7c1cf0-3396-4a39-a048-ad8d42772ea2)
![20240729_004724](https://github.com/user-attachments/assets/b0bf872b-5806-4f02-b185-60fd42d58c3b)
![20240729_004803](https://github.com/user-attachments/assets/0cc4f157-44df-45bf-8bc7-68b30a229ba4)
![image](https://github.com/user-attachments/assets/f1b3cce0-3699-4587-9a29-96d818b4e5c3)

**Comment by Cipulot** [comment]
The keyboard maintainers for Keychron need to follow the merging requirements as all the other maintainers. It's up to them to comply with the requirements for merging.

Also:

<img width="120" alt="Screenshot 2024-07-29 at 1 10 16 PM" src="https://github.com/user-attachments/assets/1080cc53-961b-4a6e-9e1a-70aad5e9cca0">

Here `our support` refers to Keychron support.
