### ISSUE TITLE
[Request] Support for Skyloong gk87

### ISSUE THREAD

**Issue by Humam-Hamdan** [the-via/keyboards#2362]
Hi, i saw that there was a PR to add support for this keyboard but it was deleted without a reason given. Is there anyway to add support?

**Comment by NaturalZh** [comment]
This project had some technical issues with the keyboard and did not fully meet VIA's requirements, so it was deleted and redone.If you are interested in this keyboard, you can visit [Skyloong/QMK](https://github.com/NaturalZh/qmk_firmware07072023) to get the latest firmware information related to this keyboard, and [Skyloong/VIA](https://github.com/JZ-Skyloong/VIA_keyboards) to learn about the VIA layout of this keyboard.You have a variety of different specifications to choose from.Currently, qmk's PR application is in progress. When qmk PR is approved for merger, it will immediately apply to VIA to merge keymaps.

**Comment by colin-purcell** [comment]
For anyone in the same boat as me, and Just to add a bit more information in the interim... this PR appears to be the one mentioned https://github.com/qmk/qmk_firmware/pull/24460

To get this working with VIA, here's a github link to the json for the gk87 (or at least, the [version of gk87 I have](https://epomaker.com/products/skyloong-gk87-qmk-via)... non-pro, blue backlight, 3 rotary knobs): https://github.com/JZ-Skyloong/VIA_keyboards/blob/gk87_bl/v3/skyloong/gk87/bl/gk87_bl_ansi.json
more models can be found at that same by poking around.

For anyone new/confused about how to use it, some basic instructions:
> - Open [usevia.app](https://usevia.app/)
> - Go to settings and enable the "Show Design tab" toggle
> - Go to the Design Tab and load the JSON firmware files downloaded in step 1
> - Go back to the "Configure" tab and authorise your keyboard
> - Edit make edits to the keyboard as you like - they are updated on the fly. You may choose to save (download) the configuration as a backup.

source: https://github.com/lukethacoder/keyboard-config

Note: The json files from the skyloong website did not work for me (despite lukethacoder's mention in the source instructions), I was only able to get the json from JZ-Skyloong github above to work (which is also linked to directly from the keyboard manual)... also my keyboard is not detected 100% of the time in VIA with the above, occasionally I have to delete the "draft definition" and reload it a couple times (I'm on Linux using the VIA appimage here https://github.com/the-via/releases)

**Comment by Humam-Hamdan** [comment]
@colin-purcell Thanks for the file + mentioning the Appimage. just a Question though, what do i do  to  "flash" the config to the board?

**Comment by NaturalZh** [comment]
> @colin-purcell Thanks for the file + mentioning the Appimage. just a Question though, what do i do to "flash" the config to the board?

@Humam-Hamdan You can download the bin at [JIKEDINGZHI/Release](https://github.com/NaturalZh/qmk_firmware07072023/releases/tag/gk87_bl_v1.0.0). JIKEDINGZHi is the factory and development of Skyloong.

**Comment by Humam-Hamdan** [comment]
@NaturalZh And what to do with it afterwards?

**Comment by NaturalZh** [comment]
> @NaturalZh And what to do with it afterwards?

* Put GK87_BL Keyboard into DFU (Bootloader) Mode ---hold esc key, then plug usb to pc ;
* Flashing the bin with [QMK Toolbox]( https://github.com/qmk/qmk_toolbox/releases);
* Restart the keyboard.

**Comment by Humam-Hamdan** [comment]
> > @NaturalZh And what to do with it afterwards?
> 
>     * Put GK87_BL Keyboard into DFU (Bootloader) Mode ---hold esc key, then plug usb to pc ;
> 
>     * Flashing the bin with [QMK Toolbox](https://github.com/qmk/qmk_toolbox/releases);
> 
>     * Restart the keyboard.

I'm on Linux, seems like there's no packaging for linux at the time

**Comment by NaturalZh** [comment]
> > > @NaturalZh And what to do with it afterwards?
> > 
> > 
> > ```
> > * Put GK87_BL Keyboard into DFU (Bootloader) Mode ---hold esc key, then plug usb to pc ;
> > 
> > * Flashing the bin with [QMK Toolbox](https://github.com/qmk/qmk_toolbox/releases);
> > 
> > * Restart the keyboard.
> > ```
> 
> I'm on Linux, seems like there's no packaging for linux at the time

Reference to [qmk / flashing your keyboard](https://docs.qmk.fm/newbs_flashing), maybe you can find a way. Wish you good lucy.

**Comment by colin-purcell** [comment]
@Humam-Hamdan 
To clarify, there are a few ways to reprogram the keyboard. I believe NaturalZh was directing you to take a prebuilt firmware and use QMK Toolbox to flash the keyboard with that prebuilt firmware. (VIA is not involed)

The way I'm doing it right now (what I described above) uses VIA (QMK Toolbox is not involved), which I loosely understand, handles no specific prebuilt firmwares. Instead, when you provide VIA with the JSON file (described above), then you can setup whatever customizations you want, then you have to "save" that config to a file, which allows you to "load" the config (which reprograms your connected keyboard on the fly). 

I'm pretty new to this myself, and that's how I understand it so far. If I've said anything wrong, someone can correct me here, but at least the details I've provided let me reprogram my own gk87 without trouble. 

Report back with your success or struggles so I know if my instructions could use improvement for you and anyone else.

**Comment by Humam-Hamdan** [comment]
@colin-purcell Yep just noticed it :) thanks
also, how did you customize the split spacebar (if you did)

**Comment by colin-purcell** [comment]
I'd start looking here:
https://docs.qmk.fm/mod_tap
https://docs.qmk.fm/feature_layers

to see if either help with what you're trying to do specifically. Special keys like the ones in those links can be set with "KEYMAP">"SPECIAL">"Any" in VIA

 For the most part you'll want to use the QMK documentation for information about programming.
 The QMK github also links to their support Discord server https://discord.gg/qmk if you get stuck or want to chat about configs

**Comment by Humam-Hamdan** [comment]
@colin-purcell Thanks mate, saved me there :)
