### ISSUE TITLE
[Request] Support for Nuphy Air 75 v2

### ISSUE THREAD

**Issue by srPeanuts** [the-via/keyboards#2388]
Hello, I cant config my Nuphy Keyboard Air 75 V2 on the new Via v3 software. Will there be a supported version for my keyboard?
Can someone please do it?

**Comment by Cipulot** [comment]
The addition of boards is the responsibility of the vendor.

Also I'd check the battery on any Nuphy board after seeing multiple boards with swollen batteries and one even exploding.
