### ISSUE TITLE
What can I do if my keyboard isn't supported?

### ISSUE THREAD

**Issue by quisys** [the-via/keyboards#247]
I have an XD87HS and it isn't supported yet. Is support planned?

I'd love to contribute but unfortunately I'm no good at programming :(

**Comment by jeffchen0124** [comment]
Not a whole lot of programming knowledge is required to add support for a keyboard. It's a lot more just formatting and following directions. MechMerlin has a really good series on youtube where he adds support for a whole bunch of keyboards. [Mechmerlin QMK/VIA playlist](https://www.youtube.com/playlist?list=PLZlceRZZjRujoE95Uum30gpmrJxNBESLl)

Before you can do anything with VIA support, you'll need to first set up QMK. Check out  [QMK Introduction](https://beta.docs.qmk.fm/tutorial/newbs) and [MechMerlin QMK Intro Playlist](https://www.youtube.com/playlist?list=PLZlceRZZjRuhgztKmHPFdnpfbnEf1dqzk)
