### ISSUE TITLE
"Any" under special key overwriting while entering

### ISSUE THREAD

**Issue by Benjaminbburn** [the-via/keyboards#280]
When trying to enter a custom keycode using the Any key under "special" it actively overwrites keys on the keyboard in the background. 
![image](https://user-images.githubusercontent.com/20584194/91373530-9c5b2480-e7e4-11ea-9982-a1964e258e06.png)

**Comment by csarmendariz** [comment]
I had the same problem and it was solved by going to "settings" and turning "Allow remapping via keyboard" off.
