### ISSUE TITLE
How to run VIA locally to test keyboard support

### ISSUE THREAD

**Issue by Pimentoso** [the-via/keyboards#32]
Hello there I'm trying to add support for a new keyboard. I took care of the QMK side, I was wondering how to try it out locally before submitting the PR here. I assume I have to compile and run the electron app locally but I can't find any direction about it. Is it the "reader" project?

Thanks!

**Comment by Wilba6582** [comment]
You can test it with the installed VIA. Enable "Show Design tab" from Settings. In Desing tab, load the definition.

**Comment by Pimentoso** [comment]
Thanks. Worked like a charm.
