### ISSUE TITLE
Some special keys do not display correctly

### ISSUE THREAD

**Issue by jja2000** [the-via/keyboards#323]
Because this bug seems to be holding back https://github.com/the-via/keyboards/pull/128 I'm making an issue.

The Big Ass Enter and maybe other partial keys do not get placed correctly into the keyboard on the configuration tab of VIA:

![Image of the bug](https://user-images.githubusercontent.com/14004235/81325461-ae2f8500-9098-11ea-8a5e-e030dfa06603.png)

See the layout PR for the json file I used

**Comment by 4pplet** [comment]
Not sure if this is related to the same bug/issue, but smaller ISO-enter keys like the one on the Apple Extended Keyboard do not show correctly either. Let me know if I should make e separate issue.

https://i.imgur.com/GQwp8QU.png

Check keyboards/src/4pplet/aekiso60_rev_a.json for .json.
https://github.com/the-via/keyboards/blob/master/src/4pplet/aekiso60_rev_a.json

Would be very appreciated if you could look into this also :)

**Comment by NiccoMlt** [comment]
Similar problem here with KPrepublic XD60 Rev. 3 when selecting row 4 layouts "Arrows" or "ISO Arrows".
The three keys are so shifted to the right to the right that I need a 21:9 aspect ratio to at least show them.

![ISO Arrows](https://user-images.githubusercontent.com/18643366/103149954-070a7580-476f-11eb-90f8-8be057bd5cf0.png)

**Comment by kb-elmo** [comment]
> 
> 
> Similar problem here with KPrepublic XD60 Rev. 3 when selecting row 4 layouts "Arrows" or "ISO Arrows".
> The three keys are so shifted to the right to the right that I need a 21:9 aspect ratio to at least show them.
> 
> ![ISO Arrows](https://user-images.githubusercontent.com/18643366/103149954-070a7580-476f-11eb-90f8-8be057bd5cf0.png)

different problem. doesn't relate to this issue.

**Comment by yiancar** [comment]
This has now been fixed
