### ISSUE TITLE
Ctrl Shift Esc to launch Task Manager does not work with {Esc`} on esc

### ISSUE THREAD

**Issue by kudiaborm** [the-via/keyboards#360]
I'm not sure how major this is but I did not ice t he behavior and figured I'd report it.

Ctrl Shift Esc to launch Task Manager does not work with {Esc`} on esc key

**Comment by NiccoMlt** [comment]
I am also experiencing your same problem after enabling VIA in QMK.

QMK has overrides for Grave Escape key: https://docs.qmk.fm/#/feature_grave_esc?id=configuration

On regular QMK, adding `GRAVE_ESC_CTRL_OVERRIDE` define to the `config.h` should be sufficient to solve your problem, but I never tried with VIA enabled, and I don't know if VIA allows to enable/disable those escapes from the application, but it seems not.
