### ISSUE TITLE
Right shift works when used but in matrix tester it does not

### ISSUE THREAD

**Issue by NiccoMlt** [the-via/keyboards#470]
I use [this layout](http://www.keyboard-layout-editor.com/##@@_c=#b5b5b5&a:3&f:2;&=ESC%0A%0A%0A%0A%60%0A%7C&_c=#cccccc&a:0&f:3;&=!%0A1%0A%0A%0A%0AF1&=/@%0A2%0A%0A%0A%0AF2&=#%0A3%0A%0A%0A%0AF3&=$%0A4%0A%0A%0A%0AF4&=%25%0A5%0A%0A%0A%0AF5&=%5E%0A6%0A%0A%0A%0AF6&=/&%0A7%0A%0A%0A%0AF7&=*%0A8%0A%0A%0A%0AF8&=(%0A9%0A%0A%0A%0AF9&=)%0A0%0A%0A%0A%0AF10&=?%0A'%0A%0A%0A%0AF11&=%5E%0A%C3%AC%0A%0A%0A%0AF12&_c=#b5b5b5&a:7&f:2;&=BKSP&_f:3;&=Del;&@_w:1.5;&=Tab&_c=#cccccc;&=Q&=W&=E&=R&=T&=Y&=U&=I&=O&=P&_a:4;&=%C3%A9%0A%C3%A8%0A%7B%0A%5B&=*%0A+%0A%7D%0A%5D&_x:0.25&c=#b5b5b5&a:7&w:1.25&h:2&w2:1.5&h2:1&x2:-0.25;&=Enter;&@_w:1.25&w2:1.75&l:true;&=Caps%20Lock&_x:0.5&c=#cccccc;&=A&=S&=D&=F&=G&=H&=J&=K&=L&_a:4;&=%C3%A7%0A%C3%B2%0A%0A/@&=%C2%B0%0A%C3%A0%0A%0A#&_a:5;&=%C2%A7%0A%C3%B9;&@_c=#b5b5b5&a:7&w:1.25;&=Shift&_c=#cccccc&a:4;&=%3E%0A%3C&_a:7;&=Z&=X&=C&=V&=B&=N&=M&_a:4;&=/;%0A,&=/:%0A.&_c=#b5b5b5&a:7&w:1.75;&=Shift&=%E2%96%B2&_c=#cccccc&a:4;&=/_%0A-;&@_c=#b5b5b5&a:7&w:1.25;&=Ctrl&_w:1.25;&=Win&_w:1.25;&=Alt&_c=#cccccc&w:6.25;&=&_c=#b5b5b5;&=Alt%20Gr&=Fn&=%E2%97%84&=%E2%96%BC&=%E2%96%BA) on a KPrepurblic XD60 Rev. 3 and everything seems to work, but VIA matrix tester doesn't recognize the right shift:
![screenshot](https://user-images.githubusercontent.com/18643366/103150046-45ecfb00-4770-11eb-9b08-bb34bddcc63c.png)

(sorry for the weird-looking window of the layout, I already [commented](https://github.com/the-via/keyboards/issues/323#issuecomment-751343266) the existing issue #323 about that display problem)

**Comment by kb-elmo** [comment]
The problem here does not relate to the layout display issue that you linked.

The keymap definition files for the XD60 boards just had a few mistakes in them which caused the optional layouts to be displayed wrong.

**Comment by NiccoMlt** [comment]
Oh ok, good to know, sorry for the confusion
