### ISSUE TITLE
Greather than (>) and less than (<) key is not supported and it is needed for ISO-ES layout

### ISSUE THREAD

**Issue by jesusignazio** [the-via/keyboards#495]
![](https://i.ibb.co/G281zRz/7cfvisietpe21.jpg)

If i bind it with the 'special'/'<' default VIA mapping, it gives a semicolon symbol, I think that it is intended to correspond to the less-than key ubication in some ISO layouts, but not for the Spanish:

![](https://i.ibb.co/s38nSXg/Captura2.png)

I didn't find any other potentially solution yet.

Keyboard: Discipline65

**Comment by Wilba6582** [comment]
The "<" in the Special section is just shift+comma (i.e. produces "<" for ANSI layouts).

You need "NUBS" (KC_NUBS) for that key. The other international keycode is "NUHS" (KC_NUHS) used for the Ç key.

**Comment by jesusignazio** [comment]
Thanks!
