### ISSUE TITLE
Support Tap-Hold Configuration options

### ISSUE THREAD

**Issue by rmaldera** [the-via/keyboards#523]
Hello,

Would it be possible to support custom values for [Tap-Hold Options](https://beta.docs.qmk.fm/using-qmk/software-features/tap_hold) in VIA?

It would be great to have support for the global options at least:

- TAPPING_TERM xxx
- PERMISSIVE_HOLD
- IGNORE_MOD_TAP_INTERRUPT
- TAPPING_FORCE_HOLD
- RETRO_TAPPING

and out of those the first three would be of great help for fast typists.

**Comment by Xelus22** [comment]
These are statically defined at compile time. This is by design with QMK. 
Hence VIA cannot change these even if they wanted to.

**Comment by rmaldera** [comment]
Just as a quick update for future readers, Vial (https://get.vial.today/) is now supporting these configurations on the fly (which work on VIA keyboards).

Although Vial's way of saving info in the keyboard is different, I hope this can be backported to Via in one way or another.
