### ISSUE TITLE
Caps Lock (as input switcher) on MacOS

### ISSUE THREAD

**Issue by LovelyAlpaca** [the-via/keyboards#551]
In VIA, the Caps Lock key locks up every key as uppercase. However, in MacOS the Caps Lock key is also able to switch input sources. There seems to be some conflicts between a locked Caps Lock key and MacOS's function to switch input sources.

https://user-images.githubusercontent.com/78362796/106576558-40a57c00-6578-11eb-9bfe-c76a69efb839.mov
A keystroke on the Caps Lock key of MacBook's built-in keyboard results in an instantly freed Caps Lock key and switched input source.

https://user-images.githubusercontent.com/78362796/106577711-a80ffb80-6579-11eb-853b-cff9428671a3.mov
In the MacOS version of VIA, a single stroke of the Caps Lock locks every key in uppercase while switching the input source, causing the problem.

**Comment by LovelyAlpaca** [comment]
KEY-DOWN - QMK: KC_CAPS Event key: CapsLock    Code: CapsLock      KeyCode: 20
KEY-DOWN - QMK:         Event key: Unidentified Code: Unidentified  KeyCode: 0
KEY-UP   - QMK: KC_CAPS Event key: CapsLock    Code: CapsLock      KeyCode: 20 in 123.000ms

This is what happens when Caps Lock key is used as the input source switcher in MacOS.

**Comment by kb-elmo** [comment]
I don't think that this is a VIA problem.
VIA is just a GUI for changing the keymap.

This is more likely an issue with the underlying firmware which is QMK.

**Comment by cythb** [comment]
https://github.com/qmk/qmk_firmware/pull/15200
See if this PR is helpful.

**Comment by stage-two** [comment]
Disabling NKRO does the job.

**Comment by yiancar** [comment]
@stage-two you are saying that the only thing needed is to disable NKRO or also change the tap delay?

**Comment by stage-two** [comment]
@yiancar just NKRO.
Tried it on: GMMK PRO, couple of Keychrons and others with Mac Mini 2018 and couple of Intel-based MBPs.
Same story everywhere: setting `NKRO_ENABLE = no` in qmk rules.mk fixes Caps Lock input source switching.

This issue seems to be unrelated to VIA itself.

**Comment by yiancar** [comment]
Thank you for the info!

**Comment by ItsRyanWu** [comment]
> @yiancar just NKRO. Tried it on: GMMK PRO, couple of Keychrons and others with Mac Mini 2018 and couple of Intel-based MBPs. Same story everywhere: setting `NKRO_ENABLE = no` in qmk rules.mk fixes Caps Lock input source switching.
> 
> This issue seems to be unrelated to VIA itself.

This works for me, awesome!
FYI in VIA you could set some key to 'Toogle NKRO' and press it to toggle it off, then you can unbind it and set to other keys you want.
![image](https://github.com/the-via/keyboards/assets/17338101/5099a1ab-4bc4-4b7b-9160-05990f553f77)
