### ISSUE TITLE
VIA not saving design from local JSON file

### ISSUE THREAD

**Issue by kshpits** [the-via/keyboards#554]
I've added support for my keyboard in QMK and made JSON file for VIA. After loading custom JSON from design tab everything is working. But after closing VIA does not recognize the board, and i need to load custom JSON again.

**Comment by Wilba6582** [comment]
Yes, loading the JSON is only for testing. You need to submit a PR to get that JSON into the repository and then after it is merged, it will be downloaded by VIA clients and you don't need to use the design tab again.

**Comment by kshpits** [comment]
Then what should i do? YMD75 board have PRODUCT_ID 0x422D in QMK repo, but in VIA repo it used by board YMDK bface https://github.com/the-via/keyboards/blob/master/src/YMDK/bface/bface.json and bface board have productid 0x4266 https://github.com/qmk/qmk_firmware/blob/master/keyboards/ymdk/bface/config.h

Which repo should change PRODUCT_ID?
