### ISSUE TITLE
How to perform changes to keyboards json definition and apply changes locally

### ISSUE THREAD

**Issue by tott** [the-via/keyboards#603]
I'm always happily hacking around in my keyboards and recently added RGB to my discipline v2. This is all working well but I am lacking the lightning configuration options in VIA as the default json definition of this keyboard sets lightning to "none". While I am aware how to change the file to support lightning options I cannot figure out how I can make VIA apply these changes. Any hints would be helpful.

Thanks for a great tool.

**Comment by kb-elmo** [comment]
you can enable the design tab function in VIA in the options.

a new tab will appear in which you can open a modified JSON file.
This "sideload" is only temporary and you will have to repeat it every time you open VIA.

**Comment by tott** [comment]
This is great - thanks. Is there any way to make this permanent ie. adding a command line option to the via launcher or is there a way to self-compile via?

**Comment by kb-elmo** [comment]
> This is great - thanks. Is there any way to make this permanent ie. adding a command line option to the via launcher or is there a way to self-compile via?

nope

**Comment by tott** [comment]
Thanks for the quick response. It's still great :100:
