### ISSUE TITLE
VIA is not detecting keyboard

### ISSUE THREAD

**Issue by kshpits** [the-via/keyboards#653]
I've added keyboard (YMD 75) ) to [VIA](https://github.com/the-via/keyboards/pull/565), but GUI app is not detecting it. If i'm loading json file from PR through design tab, then keyboard is detected.

I've tried to reflash keyboard with firmware from caniusevia.com, but no luck.

**Comment by wilba** [comment]
the file was missing .json extension. should be fixed now
