### ISSUE TITLE
Unicode Enable

### ISSUE THREAD

**Issue by flynhawaiian** [the-via/keyboards#741]
Is there a way we could have the ability use or enable unicode?  I would like the ability to have a built in paragraph key with ease.  It's something allowable in the qmk firmware, and since this is an extension I'm thinking it should be possible?

**Comment by yiancar** [comment]
I have never tried this but have you tried:
Enabling UNICODE in the rules.mk file.
Than in VIA using the any key and doing something like `UC(c)` with c being the hex file of the unicode
