### ISSUE TITLE
Some boards are not recognized for me on Via for Mac, but are working fine on Windows

### ISSUE THREAD

**Issue by briantotheyanyan** [the-via/keyboards#799]
I noticed that using the same Usb-c to A adapter for windows always works. However, the WT75-C (PCB for the 7V) and the WT65-F (Jules) aren't recognized on the same adapter for Mac. I was wondering if all boards were having issues on Mac, but some of my other boards (like the Mode 80) were able to be recognized on my Mac just fine. This is the only USB-C to A adapter I have, so I am unable to check if this is a weird adapter compatibility issue on Mac.

**Comment by krzysztofborkowski** [comment]
I'm seeing something similar with my redox. Via detects the keyboard just fine on linux but it simply doesn't work on OSX.
Unfortunately I don't have micro-usb - usb-c cable to connect the keyboard directly to macbook but I tried connecting it in two ways:
1) To dell u2719dc monitor (which is connected to macbook with usb-c cable) which works as usb hub
2) Using usb-a - micro-usb cable with usb-a - usb-c adapter

The keyboard works just fine in both cases, I'm also able to flash to firmware with QMK Toolbox/from cmd but it is not detected in Via.

**Comment by yiancar** [comment]
The issue seems to be some usb hubs and OSX. usually it works directly
