### ISSUE TITLE
HID Interface for lighting control.

### ISSUE THREAD

**Issue by gilgm12** [the-via/keyboards#803]
Is there an existing interface for VIA firmware that would allow lighting override via HID?  What would be great is an interface, key-by-key (or zone by zone if that's the hardware implementation), starting at the top left controllable element and moving in a grid pattern to the right->down.

I'd be more than happy to help with this impl - I'm not sure this is the repo for this.

Full ansi, per-key:
```
[ 0,  1,  2,  3,  4,  5,  6, .., 15]
[16, 17, 18, 19, 20, 21, 22, .., 36]
[...]
```

**Comment by kb-elmo** [comment]
VIA is only the a GUI.

What you are looking for would have to be implemented on QMK side. 
Currently something like this doesn't exist but there are plans to implement a new general purpose API that will include such functionality.

See here for more info and development status:  
https://github.com/qmk/qmk_firmware/issues/11567
