### ISSUE TITLE
Read Layout QMK Firmware side?

### ISSUE THREAD

**Issue by drashna** [the-via/keyboards#912]
aside from reading the eeprom constantly, is there a good way to read the current layout options? 

Would like to enable/disable LEDs in the rgb matrix based on the status of the layouts, but there doesn't look to be a way to do so?

**Comment by wilba** [comment]
I didn't think it worth using RAM on this, my RGB code already had separate state for layouts (like split backspace etc.) prior to the layout option stuff added to VIA. As such, maybe store state in the RGB config which acts as the cache, and then read the layout options on startup/mode change and push that into the RGB config state. If you want to patch in a "no eeprom" getter into via.c then that'll work too.

**Comment by drashna** [comment]
Yeah, but that's your rgb code. Which I have no intention of implementing.  Additionally, there are reasons other than just RGB for wanting to read that information.  Being able to do so without having to read from eeprom every time would be nice. 

So, aside from reading from the EEPROM constantly, there is no way then, without modifying core code then. Especially since the raw hid callbacks don't send the data to the kb level functions unless it's unrecognized.  if that at least passed on the info, it would be a vast improvement, just in general. 

But for now, looks like I'm sticking with this: 
```c
__attribute__((weak)) void rgb_matrix_indicators_user(void) {
#    ifdef VIA_ENABLE
    static bool     layout_2u = false;
    static uint16_t timer = 0;
    if (timer_elapsed(timer) > 500) {
        timer     = timer_read();
        layout_2u = (bool)via_get_layout_options();
    }
    if (layout_2u) {
        rgb_matrix_set_color(5, 0, 0, 0);
        rgb_matrix_set_color(7, 0, 0, 0);
    } else {
        rgb_matrix_set_color(6, 0, 0, 0);
    }
#    else
    rgb_matrix_set_color(5, 0, 0, 0);
    rgb_matrix_set_color(7, 0, 0, 0);
#    endif
}
```

**Comment by wilba** [comment]
This is what I was suggesting - store state locally, cache the layout options state, or make a change to via.c and add a "no eeprom" getter. I can add one in the next round of changes if you don't want to do it.

**Comment by drashna** [comment]
Well, I think the best solution would be to have the `raw_hid_receive_kb` be called no matter what.

That way, when changes are made (such as the layout options), that can be read by the kb level code, and cached/stored locally, rather than having to constantly read the EEPROM or stored globally.
